language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
install:
  - cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/ambuild.git && cd ambuild && python setup.py build && sudo python setup.py install
  - cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/metamod-source.git
  - cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/hl2sdk.git -b tf2 hl2sdk-tf2
  - cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/sourcemod.git && cd sourcemod && mkdir build && cd build && python ../configure.py --sdks=tf2 --no-mysql --enable-optimize && ambuild
script:
  - export SOURCEMOD_RELEASE=$(cd $TRAVIS_BUILD_DIR/../sourcemod/build/package/addons/sourcemod && pwd)
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - python $TRAVIS_BUILD_DIR/configure.py --enable-optimize --sdks=tf2
  - ambuild