language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
install:
  - CHECKOUT_DIR=$PWD
  - cd .. && git clone https://github.com/alliedmodders/ambuild.git && cd ambuild && python setup.py build && sudo python setup.py install && cd $CHECKOUT_DIR
  - cd .. && git clone https://github.com/alliedmodders/metamod-source.git && cd $CHECKOUT_DIR
  - cd .. && git clone https://github.com/alliedmodders/hl2sdk.git -b tf2 hl2sdk-tf2 && cd $CHECKOUT_DIR
  - cd .. && git clone https://github.com/alliedmodders/sourcemod.git && cd sourcemod && mkdir build && cd build && python ../configure.py --sdks=tf2 --no-mysql --enable-optimize && ambuild && cd $CHECKOUT_DIR
script:
  - SOURCEMOD_RELEASE=$(cd ../sourcemod/package/addons/sourcemod && pwd)
  - mkdir build && cd build
  - python ../configure.py --enable-optimize --sdks=tf2
  - ambuild