language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
install:
  - git clone https://github.com/alliedmodders/ambuild.git $TRAVIS_BUILD_DIR/../ambuild && cd $TRAVIS_BUILD_DIR/../ambuild && python setup.py build && sudo python setup.py install
  - git clone https://github.com/alliedmodders/metamod-source.git $TRAVIS_BUILD_DIR/../metamod-source
  - git clone https://github.com/alliedmodders/hl2sdk.git -b tf2 $TRAVIS_BUILD_DIR/../hl2sdk-tf2
  - git clone https://github.com/alliedmodders/sourcemod.git $TRAVIS_BUILD_DIR/../sourcemod && cd $TRAVIS_BUILD_DIR/../sourcemod && mkdir build && cd build && python ../configure.py --sdks=tf2 --no-mysql --enable-optimize && ambuild
script:
  - export SOURCEMOD_RELEASE=$(cd $TRAVIS_BUILD_DIR/../sourcemod/build/package/addons/sourcemod && pwd)
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - python ../configure.py --enable-optimize --sdks=tf2
  - ambuild